# Generated by Django 6.0.3 on 2026-03-17 12:36

from django.db import migrations


MODERATOR_GROUP_NAME = "Moderators"


def create_moderators_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.get_or_create(name=MODERATOR_GROUP_NAME)


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RunPython(create_moderators_group, migrations.RunPython.noop),
    ]
