# Generated by Django 6.0.3 on 2026-04-20 15:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('readable_id', models.SlugField(blank=True, max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('picture', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('location', models.CharField(blank=True, max_length=255)),
                ('moderation_status', models.CharField(choices=[('NEW', 'New'), ('FLAGGED', 'Flagged'), ('APPROVED', 'Approved'), ('REPORTED', 'Reported'), ('REJECTED', 'Rejected')], default='NEW', max_length=16)),
                ('pending_edit', models.JSONField(blank=True, default=None, help_text='Serialised pending edit fields submitted by the owner. None means no edit is awaiting moderation.', null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='added_book_stations', to=settings.AUTH_USER_MODEL)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_book_stations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('latitude__isnull', True), ('longitude__isnull', True)), models.Q(('latitude__isnull', False), ('longitude__isnull', False)), _connector='OR'), name='bookstation_lat_lon_both_or_none'), models.CheckConstraint(condition=models.Q(models.Q(('location', ''), _negated=True), models.Q(('latitude__isnull', False), ('longitude__isnull', False)), _connector='OR'), name='bookstation_location_or_geolocation')],
            },
        ),
    ]
