# Generated by Django 6.0.3 on 2026-03-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_stations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookstation",
            name="picture",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
