# Generated by Django 6.0.3 on 2026-03-10 11:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_stations", "0005_move_item_model_to_items_app"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookstation",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name="bookstation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("latitude__isnull", True), ("longitude__isnull", True)),
                    models.Q(("latitude__isnull", False), ("longitude__isnull", False)),
                    _connector="OR",
                ),
                name="bookstation_lat_lon_both_or_none",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookstation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("location", ""), _negated=True),
                    models.Q(("latitude__isnull", False), ("longitude__isnull", False)),
                    _connector="OR",
                ),
                name="bookstation_location_or_geolocation",
            ),
        ),
    ]
