# Generated by Django 6.0.3 on 2026-03-16 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_stations', '0006_alter_bookstation_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstation',
            name='claimed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_book_stations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookstation',
            name='moderation_status',
            field=models.CharField(choices=[('PENDING', 'Pending moderation'), ('APPROVED', 'Approved')], default='PENDING', max_length=16),
        ),
    ]
