# Generated by Django 6.0.3 on 2026-03-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_stations', '0008_approve_existing_stations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstation',
            name='moderation_status',
            field=models.CharField(choices=[('PENDING', 'Pending moderation'), ('APPROVED', 'Approved')], default='APPROVED', max_length=16),
        ),
    ]
