# Generated by Django 6.0.3 on 2026-03-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_stations', '0009_alter_bookstation_moderation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstation',
            name='pending_edit',
            field=models.JSONField(blank=True, default=None, help_text='Serialised pending edit fields submitted by the owner. None means no edit is awaiting moderation.', null=True),
        ),
    ]
