# Generated by Django 6.0.3 on 2026-04-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_stations', '0014_migrate_pending_to_flagged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstation',
            name='moderation_status',
            field=models.CharField(choices=[('NEW', 'New'), ('FLAGGED', 'Flagged'), ('APPROVED', 'Approved'), ('REPORTED', 'Reported'), ('REJECTED', 'Rejected')], default='NEW', max_length=16),
        ),
    ]
