# Generated by Django 6.0.3 on 2026-09-30 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_stations', '0015_alter_bookstation_moderation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookstation',
            name='claimed_by',
        ),
        migrations.RemoveField(
            model_name='bookstation',
            name='moderation_status',
        ),
        migrations.RemoveField(
            model_name='bookstation',
            name='pending_edit',
        ),
    ]
