# Generated by Django 6.0.3 on 2026-10-10 15:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_stations', '0017_migrate_legacy_picture_urls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StationVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='book_stations.bookstation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visited_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'station'), name='unique_station_visit_per_user')],
            },
        ),
    ]
