"""
Django settings for share_books project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

from django_recaptcha.constants import TEST_PUBLIC_KEY as _RECAPTCHA_TEST_PUBLIC_KEY
from django_recaptcha.constants import TEST_PRIVATE_KEY as _RECAPTCHA_TEST_PRIVATE_KEY

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_o@ek3vuu9e07uv)v$h-3z817b@sx&q#f600#h8hw#ov#^+xut'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]']

# Trust localhost origins for local development.  Once CSRF_TRUSTED_ORIGINS is
# set Django enforces strict origin checking on every POST, so all origins that
# the browser may report (with or without an explicit port) must be listed.
# Both http:// and https:// are included because VS Code port-forwarding and
# some Codespaces setups serve the forwarded port over HTTPS even for localhost.
CSRF_TRUSTED_ORIGINS = [
    'http://localhost',
    'http://localhost:8000',
    'https://localhost',
    'https://localhost:8000',
    'http://127.0.0.1',
    'http://127.0.0.1:8000',
    'https://127.0.0.1',
    'https://127.0.0.1:8000',
]

# GitHub Codespaces support
# When CODESPACE_NAME is set (automatically by Codespaces), requests arrive through
# a reverse proxy that rewrites the host/scheme.  Enable the proxy-header settings
# so request.build_absolute_uri() returns the correct public URL
# (e.g. https://<id>-8000.app.github.dev) rather than http://localhost:8000.
_codespace_name = os.environ.get('CODESPACE_NAME')
if _codespace_name:
    USE_X_FORWARDED_HOST = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    ALLOWED_HOSTS += ['.app.github.dev']
    # Also trust the public Codespaces URL so POSTs from the forwarded-port
    # browser tab pass origin checking.
    CSRF_TRUSTED_ORIGINS += ['https://*.app.github.dev']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_recaptcha',
    'core',
    'book_stations',
    'items',
    'movements',
    'users',
    'moderation',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'share_books.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'moderation.context_processors.moderator_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'share_books.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Email settings
# In production set EMAIL_BACKEND and related vars via environment variables.
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend',
)
DEFAULT_FROM_EMAIL = os.environ.get(
    'DEFAULT_FROM_EMAIL',
    'noreply@sharebooks.example.com',
)

# Google reCAPTCHA v2 keys
# Default to Google's public test keys for local development.
# In production, set RECAPTCHA_PUBLIC_KEY and RECAPTCHA_PRIVATE_KEY via environment variables.
RECAPTCHA_PUBLIC_KEY = os.environ.get('RECAPTCHA_PUBLIC_KEY', _RECAPTCHA_TEST_PUBLIC_KEY)
RECAPTCHA_PRIVATE_KEY = os.environ.get('RECAPTCHA_PRIVATE_KEY', _RECAPTCHA_TEST_PRIVATE_KEY)

# Only suppress the test-key system check when DEBUG is True and the test keys are actually
# in use.  In production (DEBUG=False) or with real keys, the check runs normally.
_using_recaptcha_test_keys = (
    RECAPTCHA_PUBLIC_KEY == _RECAPTCHA_TEST_PUBLIC_KEY
    or RECAPTCHA_PRIVATE_KEY == _RECAPTCHA_TEST_PRIVATE_KEY
)
SILENCED_SYSTEM_CHECKS = (
    ['django_recaptcha.recaptcha_test_key_error'] if DEBUG and _using_recaptcha_test_keys else []
)
