# Generated by Django 6.0.3 on 2026-03-10 12:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("book_stations", "0006_alter_bookstation_location_and_more"),
        ("items", "0002_enforce_station_status_consistency"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Movement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("TAKEN_OUT", "Taken out"),
                            ("PLACED_IN", "Placed in"),
                            ("MARKED_LOST", "Marked lost"),
                            ("MARKED_FOUND", "Marked found"),
                            ("TRANSFERRED", "Transferred"),
                            ("CREATED", "Created"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "from_book_station",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movements_from",
                        to="book_stations.bookstation",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="items.item",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reported_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_book_station",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movements_to",
                        to="book_stations.bookstation",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp", "-id"],
                "indexes": [
                    models.Index(
                        fields=["item", "timestamp"], name="movements_item_time_idx"
                    ),
                    models.Index(fields=["movement_type"], name="movements_type_idx"),
                ],
            },
        ),
    ]
