# Generated by Django 6.0.3 on 2026-04-20 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book_stations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('item_type', models.CharField(choices=[('BOOK', 'Book'), ('MAGAZINE', 'Magazine'), ('DVD', 'DVD'), ('OTHER', 'Other')], default='BOOK', max_length=16)),
                ('status', models.CharField(choices=[('AT_BOOK_STATION', 'At book station'), ('TAKEN_OUT', 'Taken out'), ('LOST', 'Lost'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=24)),
                ('last_activity', models.DateField(blank=True, null=True)),
                ('moderation_status', models.CharField(choices=[('NEW', 'New'), ('FLAGGED', 'Flagged'), ('APPROVED', 'Approved'), ('REPORTED', 'Reported'), ('REJECTED', 'Rejected')], default='NEW', max_length=16)),
                ('pending_edit', models.JSONField(blank=True, default=None, help_text='Serialised pending edit fields submitted by the owner. None means no edit is awaiting moderation.', null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='added_items', to=settings.AUTH_USER_MODEL)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_items', to=settings.AUTH_USER_MODEL)),
                ('current_book_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_items', to='book_stations.bookstation')),
                ('last_seen_at', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_seen_items', to='book_stations.bookstation')),
            ],
            options={
                'ordering': ['title', 'id'],
                'indexes': [models.Index(fields=['status', 'current_book_station'], name='book_statio_status_ea334b_idx'), models.Index(fields=['item_type'], name='book_statio_item_ty_1d68a8_idx'), models.Index(fields=['last_activity'], name='book_statio_last_ac_6c1fa4_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('status', 'AT_BOOK_STATION'), _negated=True), ('current_book_station__isnull', False), _connector='OR'), name='item_station_required_when_at_station'), models.CheckConstraint(condition=models.Q(('status', 'AT_BOOK_STATION'), ('current_book_station__isnull', True), _connector='OR'), name='item_station_must_be_empty_unless_at_station')],
            },
        ),
    ]
