# Generated by Django 6.0.3 on 2026-03-16 15:51

from django.db import migrations


def approve_existing_items(apps, schema_editor):
    # Default is APPROVED, so this is a no-op for fresh databases.
    # Kept as a safety net for any records that somehow ended up as PENDING.
    Item = apps.get_model("items", "Item")
    Item.objects.filter(moderation_status="PENDING").update(moderation_status="APPROVED")


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_claimed_by_item_moderation_status'),
    ]

    operations = [
        migrations.RunPython(approve_existing_items, migrations.RunPython.noop),
    ]
