# Generated by Django 6.0.3 on 2026-03-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_item_pending_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='moderation_status',
            field=models.CharField(choices=[('PENDING', 'Pending moderation'), ('APPROVED', 'Approved'), ('REPORTED', 'Reported')], default='APPROVED', max_length=16),
        ),
    ]
