# Generated by Django 6.0.3 on 2026-03-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_alter_item_moderation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='moderation_status',
            field=models.CharField(choices=[('PENDING', 'Pending moderation'), ('APPROVED', 'Approved'), ('REPORTED', 'Reported'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=16),
        ),
    ]
