# Generated by Django 6.0.3 on 2026-09-30 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_alter_item_moderation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='claimed_by',
        ),
        migrations.RemoveField(
            model_name='item',
            name='moderation_status',
        ),
        migrations.RemoveField(
            model_name='item',
            name='pending_edit',
        ),
    ]
