# Generated by Django 6.0.3 on 2026-04-20 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book_stations', '0001_initial'),
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ITEM_APPROVED', 'Item approved'), ('ITEM_REJECTED', 'Item rejected'), ('ITEM_EDIT_APPROVED', 'Item edit approved'), ('ITEM_EDIT_REJECTED', 'Item edit rejected'), ('STATION_APPROVED', 'Station approved'), ('STATION_REJECTED', 'Station rejected'), ('STATION_EDIT_APPROVED', 'Station edit approved'), ('STATION_EDIT_REJECTED', 'Station edit rejected'), ('REPORTED_ITEM_APPROVED', 'Reported item approved'), ('REPORTED_ITEM_REJECTED', 'Reported item rejected'), ('REPORTED_STATION_APPROVED', 'Reported station approved'), ('REPORTED_STATION_REJECTED', 'Reported station rejected')], max_length=32)),
                ('from_status', models.CharField(blank=True, max_length=32)),
                ('to_status', models.CharField(blank=True, max_length=32)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('book_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_logs', to='book_stations.bookstation')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_logs', to='items.item')),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moderation_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
