# Generated by Django 6.0.3 on 2026-03-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationlog',
            name='action',
            field=models.CharField(choices=[('ITEM_APPROVED', 'Item approved'), ('ITEM_REJECTED', 'Item rejected'), ('ITEM_EDIT_APPROVED', 'Item edit approved'), ('ITEM_EDIT_REJECTED', 'Item edit rejected'), ('STATION_APPROVED', 'Station approved'), ('STATION_REJECTED', 'Station rejected'), ('STATION_EDIT_APPROVED', 'Station edit approved'), ('STATION_EDIT_REJECTED', 'Station edit rejected')], max_length=32),
        ),
    ]
