# Generated by Django 6.0.3 on 2026-03-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_alter_moderationlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationlog',
            name='action',
            field=models.CharField(choices=[('ITEM_APPROVED', 'Item approved'), ('ITEM_REJECTED', 'Item rejected'), ('ITEM_EDIT_APPROVED', 'Item edit approved'), ('ITEM_EDIT_REJECTED', 'Item edit rejected'), ('STATION_APPROVED', 'Station approved'), ('STATION_REJECTED', 'Station rejected'), ('STATION_EDIT_APPROVED', 'Station edit approved'), ('STATION_EDIT_REJECTED', 'Station edit rejected'), ('REPORTED_ITEM_APPROVED', 'Reported item approved'), ('REPORTED_ITEM_REJECTED', 'Reported item rejected'), ('REPORTED_STATION_APPROVED', 'Reported station approved'), ('REPORTED_STATION_REJECTED', 'Reported station rejected')], max_length=32),
        ),
    ]
