# Generated by Django 6.0.3 on 2026-09-30 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0003_alter_moderationlog_action'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModerationLog',
        ),
    ]
